//! Identifiers: entry ids (UUIDv7), content hashes (SHA-256).

use minicbor::{decode, encode, Decoder, Encoder};
use sha2::{Digest, Sha256};
use std::fmt;

/// 128-bit entry / batch id. Generated by clients as UUIDv7.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Id(pub [u8; 16]);

/// The reserved vault-settings entry (DESIGN §3.3).
pub const VAULT_SETTINGS_ID: Id = Id([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]);

impl Id {
    /// A UUIDv7 from a unix-ms timestamp and 10 random bytes (sans-IO: the caller supplies randomness).
    pub fn new_v7(unix_ms: u64, rand: [u8; 10]) -> Id {
        let mut b = [0u8; 16];
        b[..6].copy_from_slice(&unix_ms.to_be_bytes()[2..]);
        b[6..].copy_from_slice(&rand);
        b[6] = 0x70 | (b[6] & 0x0f); // version 7
        b[8] = 0x80 | (b[8] & 0x3f); // RFC 4122 variant
        Id(b)
    }
    /// Deterministic id derived from arbitrary bytes (used for server-generated trash batch ids).
    pub fn derive(parts: &[&[u8]]) -> Id {
        let mut h = Sha256::new();
        for p in parts {
            h.update((p.len() as u64).to_le_bytes());
            h.update(p);
        }
        let d = h.finalize();
        let mut b = [0u8; 16];
        b.copy_from_slice(&d[..16]);
        b[6] = (b[6] & 0x0f) | 0x80; // UUIDv8 "custom"
        b[8] = (b[8] & 0x3f) | 0x80;
        Id(b)
    }
    pub fn from_slice(b: &[u8]) -> Option<Id> {
        <[u8; 16]>::try_from(b).ok().map(Id)
    }
    pub fn parse(s: &str) -> Option<Id> {
        let h: String = s.chars().filter(|c| *c != '-').collect();
        let v = hex::decode(h).ok()?;
        Id::from_slice(&v)
    }
    pub fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

impl fmt::Display for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let h = hex::encode(self.0);
        write!(
            f,
            "{}-{}-{}-{}-{}",
            &h[0..8],
            &h[8..12],
            &h[12..16],
            &h[16..20],
            &h[20..32]
        )
    }
}
impl fmt::Debug for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Id({})", &hex::encode(self.0)[20..32])
    }
}

impl<C> encode::Encode<C> for Id {
    fn encode<W: encode::Write>(
        &self,
        e: &mut Encoder<W>,
        _: &mut C,
    ) -> Result<(), encode::Error<W::Error>> {
        e.bytes(&self.0)?;
        Ok(())
    }
}
impl<'b, C> decode::Decode<'b, C> for Id {
    fn decode(d: &mut Decoder<'b>, _: &mut C) -> Result<Self, decode::Error> {
        Id::from_slice(d.bytes()?).ok_or_else(|| decode::Error::message("id must be 16 bytes"))
    }
}

/// SHA-256 content hash of a blob (D4).
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct Hash(pub [u8; 32]);

impl Hash {
    pub fn of(bytes: &[u8]) -> Hash {
        Hash(Sha256::digest(bytes).into())
    }
    pub fn from_slice(b: &[u8]) -> Option<Hash> {
        <[u8; 32]>::try_from(b).ok().map(Hash)
    }
    pub fn parse_hex(s: &str) -> Option<Hash> {
        if s.len() != 64 || s.bytes().any(|c| c.is_ascii_uppercase()) {
            return None;
        }
        Hash::from_slice(&hex::decode(s).ok()?)
    }
    pub fn to_hex(&self) -> String {
        hex::encode(self.0)
    }
}
impl fmt::Display for Hash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex())
    }
}
impl fmt::Debug for Hash {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Hash({})", &self.to_hex()[..12])
    }
}
impl<C> encode::Encode<C> for Hash {
    fn encode<W: encode::Write>(
        &self,
        e: &mut Encoder<W>,
        _: &mut C,
    ) -> Result<(), encode::Error<W::Error>> {
        e.bytes(&self.0)?;
        Ok(())
    }
}
impl<'b, C> decode::Decode<'b, C> for Hash {
    fn decode(d: &mut Decoder<'b>, _: &mut C) -> Result<Self, decode::Error> {
        Hash::from_slice(d.bytes()?).ok_or_else(|| decode::Error::message("hash must be 32 bytes"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn id_roundtrip() {
        let id = Id::new_v7(1_700_000_000_000, [7; 10]);
        assert_eq!(Id::parse(&id.to_string()), Some(id));
        let b = minicbor::to_vec(id).unwrap();
        assert_eq!(minicbor::decode::<Id>(&b).unwrap(), id);
        assert!(Id::new_v7(1, [0; 10]) < Id::new_v7(2, [0; 10]));
    }
    #[test]
    fn hash_hex() {
        let h = Hash::of(b"abc");
        assert_eq!(
            h.to_hex(),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(Hash::parse_hex(&h.to_hex()), Some(h));
    }
}
