//! Git tracking of the mirror (DESIGN §13) using the `git` binary. Attachments are excluded by
//! default through `.git/info/exclude` (so no generated file can collide with a vault file); set
//! `JESS_GIT_INCLUDE_ATTACHMENTS=true` to include them, plus `JESS_GIT_LFS=true` for Git LFS.
//! Every failure is non-fatal: it is logged, retried with backoff and shown in admin status.

use crate::mirror::Changes;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

#[derive(Clone, Debug)]
pub struct GitConfig {
    pub repo: PathBuf,
    pub key_dir: PathBuf,
    pub remote: Option<String>,
    pub include_attachments: bool,
    pub lfs: bool,
}

#[derive(Debug)]
pub struct GitError(pub String);

impl std::fmt::Display for GitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

type R<T> = std::result::Result<T, GitError>;

/// Runs a command with a timeout, returning stdout.
pub fn run(cmd: &mut Command, timeout: Duration) -> R<String> {
    let mut child = cmd
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| GitError(format!("spawn {:?}: {e}", cmd.get_program())))?;
    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) if start.elapsed() > timeout => {
                let _ = child.kill();
                let _ = child.wait();
                return Err(GitError(format!(
                    "{:?} timed out",
                    cmd.get_args().collect::<Vec<_>>()
                )));
            }
            Ok(None) => std::thread::sleep(Duration::from_millis(20)),
            Err(e) => return Err(GitError(e.to_string())),
        }
    }
    let out = child
        .wait_with_output()
        .map_err(|e| GitError(e.to_string()))?;
    if out.status.success() {
        Ok(String::from_utf8_lossy(&out.stdout).to_string())
    } else {
        Err(GitError(format!(
            "{:?} failed: {}",
            cmd.get_args().collect::<Vec<_>>(),
            String::from_utf8_lossy(&out.stderr).trim()
        )))
    }
}

pub struct Git {
    pub cfg: GitConfig,
}

impl Git {
    fn git(&self) -> Command {
        let mut c = Command::new("git");
        c.current_dir(&self.cfg.repo)
            .env("GIT_TERMINAL_PROMPT", "0")
            .env("LC_ALL", "C");
        let key = self.cfg.key_dir.join("deploy_key");
        let kh = self.cfg.key_dir.join("known_hosts");
        c.env("GIT_SSH_COMMAND", format!("ssh -i {} -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile={}", key.display(), kh.display()));
        c
    }

    pub fn available() -> bool {
        Command::new("git")
            .arg("--version")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    }

    /// Initialises the repo (idempotent), writes excludes/attributes and configures the remote.
    pub fn init(&self) -> R<()> {
        let t = Duration::from_secs(60);
        if !self.cfg.repo.join(".git").exists() {
            run(self.git().args(["init", "-q"]), t)?;
            run(
                self.git().args(["symbolic-ref", "HEAD", "refs/heads/main"]),
                t,
            )?;
        }
        run(self.git().args(["config", "user.name", "Jess"]), t)?;
        run(
            self.git().args(["config", "user.email", "jess@localhost"]),
            t,
        )?;
        run(self.git().args(["config", "core.quotepath", "false"]), t)?;
        run(self.git().args(["config", "gc.auto", "256"]), t)?;
        let info = self.cfg.repo.join(".git/info");
        std::fs::create_dir_all(&info).map_err(|e| GitError(e.to_string()))?;
        let mut exclude = String::from("# Generated by Jess\n.jess-tmp-*\n.jess-generated\n");
        if !self.cfg.include_attachments {
            exclude.push_str("# Attachments are excluded (JESS_GIT_INCLUDE_ATTACHMENTS=false)\n*\n!*/\n!*.md\n!*.MD\n!*.Md\n!*.mD\n");
        }
        std::fs::write(info.join("exclude"), exclude).map_err(|e| GitError(e.to_string()))?;
        let attrs = if self.cfg.include_attachments && self.cfg.lfs {
            let mut a = String::new();
            for ext in [
                "pdf", "png", "jpg", "jpeg", "gif", "webp", "heic", "heif", "svg", "bmp", "avif",
                "tif", "tiff", "mp3", "m4a", "wav", "ogg", "mp4", "webm", "mov", "zip", "docx",
                "canvas",
            ] {
                a.push_str(&format!("*.{ext} filter=lfs diff=lfs merge=lfs -text\n*.{} filter=lfs diff=lfs merge=lfs -text\n", ext.to_uppercase()));
            }
            let _ = run(self.git().args(["lfs", "install", "--local"]), t);
            a
        } else {
            String::new()
        };
        std::fs::write(info.join("attributes"), attrs).map_err(|e| GitError(e.to_string()))?;
        if let Some(remote) = &self.cfg.remote {
            let have = run(self.git().args(["remote"]), t)?;
            if have.lines().any(|l| l == "origin") {
                run(self.git().args(["remote", "set-url", "origin", remote]), t)?;
            } else {
                run(self.git().args(["remote", "add", "origin", remote]), t)?;
            }
        }
        Ok(())
    }

    /// Generates the ed25519 deploy key on first run; returns the public key.
    pub fn deploy_key(&self) -> R<String> {
        let key = self.cfg.key_dir.join("deploy_key");
        if !key.exists() {
            std::fs::create_dir_all(&self.cfg.key_dir).map_err(|e| GitError(e.to_string()))?;
            run(
                Command::new("ssh-keygen")
                    .args([
                        "-q",
                        "-t",
                        "ed25519",
                        "-N",
                        "",
                        "-C",
                        "jess-deploy-key",
                        "-f",
                    ])
                    .arg(&key),
                Duration::from_secs(30),
            )?;
        }
        std::fs::read_to_string(key.with_extension("pub"))
            .map(|s| s.trim().to_string())
            .map_err(|e| GitError(e.to_string()))
    }

    /// Commits everything staged; returns the commit id if something was committed.
    pub fn commit(&self, message: &str) -> R<Option<String>> {
        let t = Duration::from_secs(600);
        run(self.git().args(["add", "-A"]), t)?;
        let st = self
            .git()
            .args(["diff", "--cached", "--quiet"])
            .status()
            .map_err(|e| GitError(e.to_string()))?;
        if st.success() {
            return Ok(None);
        }
        run(
            self.git()
                .args(["commit", "-q", "--no-verify", "-m", message]),
            t,
        )?;
        let id = run(self.git().args(["rev-parse", "HEAD"]), t)?;
        let _ = run(self.git().args(["gc", "--auto", "--quiet"]), t);
        Ok(Some(id.trim().to_string()))
    }

    pub fn gc_full(&self) -> R<()> {
        run(
            self.git().args(["gc", "--quiet"]),
            Duration::from_secs(1800),
        )
        .map(|_| ())
    }

    pub fn push(&self) -> R<()> {
        if self.cfg.remote.is_none() {
            return Ok(());
        }
        run(
            self.git()
                .args(["push", "-q", "origin", "HEAD:refs/heads/main"]),
            Duration::from_secs(600),
        )
        .map(|_| ())
    }

    pub fn log_count(&self) -> usize {
        run(
            self.git().args(["rev-list", "--count", "HEAD"]),
            Duration::from_secs(30),
        )
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0)
    }
}

/// `Jess: 3 edited, 1 added, 1 renamed (Old → New), 2 attachments` plus a file list.
pub fn commit_message(c: &Changes) -> String {
    let mut parts = Vec::new();
    let notes = |v: &Vec<String>| {
        v.iter()
            .filter(|p| p.to_lowercase().ends_with(".md"))
            .count()
    };
    let n_edit = notes(&c.edited);
    let n_add = notes(&c.added);
    let n_del = notes(&c.deleted);
    if n_edit > 0 {
        parts.push(format!("{n_edit} edited"));
    }
    if n_add > 0 {
        parts.push(format!("{n_add} added"));
    }
    if n_del > 0 {
        parts.push(format!("{n_del} deleted"));
    }
    if !c.renamed.is_empty() {
        let first = &c.renamed[0];
        let short = |p: &str| {
            p.rsplit('/')
                .next()
                .unwrap_or(p)
                .trim_end_matches(".md")
                .to_string()
        };
        if c.renamed.len() == 1 {
            parts.push(format!(
                "1 renamed ({} → {})",
                short(&first.0),
                short(&first.1)
            ));
        } else {
            parts.push(format!("{} renamed", c.renamed.len()));
        }
    }
    let other = c.added.len() + c.edited.len() + c.deleted.len() - n_add - n_edit - n_del;
    if other > 0 || c.attachments > 0 {
        parts.push(format!("{} attachments", other.max(c.attachments)));
    }
    if parts.is_empty() {
        parts.push("sync".into());
    }
    let mut msg = format!("Jess: {}\n\n", parts.join(", "));
    let mut lines: Vec<String> = Vec::new();
    lines.extend(c.added.iter().map(|p| format!("A {p}")));
    lines.extend(c.edited.iter().map(|p| format!("M {p}")));
    lines.extend(c.deleted.iter().map(|p| format!("D {p}")));
    lines.extend(c.renamed.iter().map(|(a, b)| format!("R {a} -> {b}")));
    lines.sort();
    lines.dedup();
    for l in lines.iter().take(500) {
        msg.push_str(l);
        msg.push('\n');
    }
    if lines.len() > 500 {
        msg.push_str(&format!("… and {} more\n", lines.len() - 500));
    }
    msg
}

pub fn repo_exists(p: &Path) -> bool {
    p.join(".git").exists()
}
