//! One-way, read-only mirror of the vault as plain files (DESIGN §13). Reads `jess.db` through
//! its own read-only connection (WAL snapshot; never blocks the writer) and keeps its own state
//! in `mirror-state.db`. Text is written atomically (temp + fsync + rename + dir fsync); blobs are
//! hardlinked from the blob store (→ reflink → copy). Nothing ever reads the mirror back.

use crate::blobfs::{fsync_dir, BlobFs};
use crate::db;
use crate::error::{Error, Result};
use crate::vault_io::Snapshot;
use jess_core::projection::{project, Options, Source};
use jess_core::{Hash, Id};
use rusqlite::{params, Connection, OptionalExtension};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

pub const MARKER: &str = ".jess-generated";
pub const README: &str = "README-GENERATED.md";

const README_TEXT: &str = "# Generated by Jess\n\nThis folder is a read-only mirror of a Jess vault, regenerated automatically from the\nJess database. **Edits made here are overwritten and never synced back.** Edit your notes in\nJess instead. `jess rebuild-mirror` regenerates it from scratch.\n";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LinkMode {
    Hardlink,
    Reflink,
    Copy,
}

#[derive(Debug, Default, Clone)]
pub struct Changes {
    pub added: Vec<String>,
    pub edited: Vec<String>,
    pub deleted: Vec<String>,
    /// (old path, new path) for entries whose path changed.
    pub renamed: Vec<(String, String)>,
    pub attachments: usize,
}

impl Changes {
    pub fn is_empty(&self) -> bool {
        self.added.is_empty()
            && self.edited.is_empty()
            && self.deleted.is_empty()
            && self.renamed.is_empty()
    }
    pub fn absorb(&mut self, o: Changes) {
        self.added.extend(o.added);
        self.edited.extend(o.edited);
        self.deleted.extend(o.deleted);
        self.renamed.extend(o.renamed);
        self.attachments += o.attachments;
    }
}

pub struct Mirror {
    pub root: PathBuf,
    state: Connection,
    db_path: PathBuf,
    fs: BlobFs,
    pub mode: Option<LinkMode>,
    pub durable: bool,
}

#[derive(Clone, Debug)]
struct Row {
    entry: Id,
    kind: String,
    hash: Vec<u8>,
    size: i64,
    mtime: i64,
}

fn mtime_of(m: &fs::Metadata) -> i64 {
    m.modified()
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_nanos() as i64)
        .unwrap_or(0)
}

impl Mirror {
    pub fn open(
        root: PathBuf,
        state_path: &Path,
        db_path: PathBuf,
        fs: BlobFs,
        durable: bool,
    ) -> Result<Mirror> {
        fs::create_dir_all(&root)?;
        let state = Connection::open(state_path)?;
        state.pragma_update(None, "journal_mode", "WAL")?;
        state.pragma_update(None, "synchronous", if durable { "FULL" } else { "OFF" })?;
        state.execute_batch(
            "CREATE TABLE IF NOT EXISTS files(path TEXT PRIMARY KEY, entry BLOB, kind TEXT NOT NULL, hash BLOB, size INTEGER, mtime INTEGER);
             CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY, value INTEGER NOT NULL);",
        )?;
        let mut m = Mirror {
            root,
            state,
            db_path,
            fs,
            mode: None,
            durable,
        };
        m.write_markers()?;
        m.recover()?;
        Ok(m)
    }

    pub fn last_seq(&self) -> u64 {
        self.state
            .query_row("SELECT value FROM meta WHERE key = 'last_seq'", [], |r| {
                r.get::<_, i64>(0)
            })
            .optional()
            .ok()
            .flatten()
            .unwrap_or(0) as u64
    }

    fn set_last_seq(&self, s: u64) -> Result<()> {
        self.state.execute("INSERT INTO meta(key, value) VALUES ('last_seq', ?1) ON CONFLICT(key) DO UPDATE SET value = excluded.value", [s as i64])?;
        Ok(())
    }

    fn write_markers(&self) -> Result<()> {
        let r = self.root.join(README);
        if fs::read_to_string(&r).ok().as_deref() != Some(README_TEXT) {
            self.atomic_bytes(&r, README_TEXT.as_bytes())?;
        }
        let m = self.root.join(MARKER);
        if !m.exists() {
            self.atomic_bytes(&m, b"This directory is generated by Jess. Do not edit.\n")?;
        }
        Ok(())
    }

    /// Startup repair: remove stray temp files; forget files whose size/mtime no longer match.
    fn recover(&mut self) -> Result<()> {
        let mut stack = vec![self.root.clone()];
        while let Some(d) = stack.pop() {
            let Ok(rd) = fs::read_dir(&d) else { continue };
            for e in rd.flatten() {
                let name = e.file_name().to_string_lossy().to_string();
                if name == ".git" {
                    continue;
                }
                let ft = e.file_type()?;
                if ft.is_dir() {
                    stack.push(e.path());
                } else if name.starts_with(".jess-tmp-") {
                    let _ = fs::remove_file(e.path());
                }
            }
        }
        let rows = self.rows()?;
        let tx = self.state.unchecked_transaction()?;
        for (p, r) in rows {
            if r.kind == "dir" {
                continue;
            }
            let ok = fs::symlink_metadata(self.root.join(&p))
                .map(|m| m.len() as i64 == r.size && mtime_of(&m) == r.mtime)
                .unwrap_or(false);
            if !ok {
                tx.execute("DELETE FROM files WHERE path = ?1", [&p])?;
            }
        }
        tx.commit()?;
        Ok(())
    }

    fn rows(&self) -> Result<BTreeMap<String, Row>> {
        let mut st = self
            .state
            .prepare("SELECT path, entry, kind, hash, size, mtime FROM files")?;
        let v = st
            .query_map([], |r| {
                let e: Vec<u8> = r.get(1)?;
                Ok((
                    r.get::<_, String>(0)?,
                    Row {
                        entry: Id::from_slice(&e).unwrap_or_default(),
                        kind: r.get(2)?,
                        hash: r.get::<_, Option<Vec<u8>>>(3)?.unwrap_or_default(),
                        size: r.get::<_, Option<i64>>(4)?.unwrap_or(0),
                        mtime: r.get::<_, Option<i64>>(5)?.unwrap_or(0),
                    },
                ))
            })?
            .collect::<std::result::Result<BTreeMap<_, _>, _>>()?;
        Ok(v)
    }

    fn tmp_in(&self, dir: &Path) -> PathBuf {
        let mut b = [0u8; 8];
        rand::Rng::fill(&mut rand::thread_rng(), &mut b);
        dir.join(format!(".jess-tmp-{}", hex::encode(b)))
    }

    fn atomic_bytes(&self, target: &Path, bytes: &[u8]) -> Result<()> {
        let dir = target.parent().expect("parent");
        fs::create_dir_all(dir)?;
        let tmp = self.tmp_in(dir);
        let mut f = fs::File::create(&tmp)?;
        f.write_all(bytes)?;
        if self.durable {
            f.sync_all()?;
        }
        drop(f);
        fs::rename(&tmp, target)?;
        Ok(())
    }

    fn link_blob(&mut self, h: &Hash, target: &Path) -> Result<()> {
        use std::os::unix::fs::MetadataExt;
        let src = self.fs.path(h);
        // Already a hardlink of this blob: nothing to do.
        if let (Ok(a), Ok(b)) = (fs::metadata(&src), fs::symlink_metadata(target)) {
            if a.dev() == b.dev() && a.ino() == b.ino() {
                return Ok(());
            }
        }
        let dir = target.parent().expect("parent");
        fs::create_dir_all(dir)?;
        let tmp = self.tmp_in(dir);
        let mode = self.mode.unwrap_or(LinkMode::Hardlink);
        let r = match mode {
            LinkMode::Hardlink => fs::hard_link(&src, &tmp),
            LinkMode::Reflink => reflink(&src, &tmp),
            LinkMode::Copy => fs::copy(&src, &tmp).map(|_| ()),
        };
        match r {
            Ok(()) => {
                self.mode.get_or_insert(mode);
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => return Err(e.into()),
            Err(e) => {
                let _ = fs::remove_file(&tmp);
                let next = match mode {
                    LinkMode::Hardlink => LinkMode::Reflink,
                    LinkMode::Reflink => LinkMode::Copy,
                    LinkMode::Copy => return Err(e.into()),
                };
                tracing::warn!("mirror: {mode:?} failed ({e}); falling back to {next:?}");
                self.mode = Some(next);
                return self.link_blob(h, target);
            }
        }
        if self.mode == Some(LinkMode::Copy) && self.durable {
            fs::File::open(&tmp)?.sync_all()?;
        }
        fs::rename(&tmp, target)?;
        // rename() is a no-op when both names are links to the same inode; drop the temp name.
        let _ = fs::remove_file(&tmp);
        Ok(())
    }

    /// Brings the mirror up to date with the database. Returns what changed.
    pub fn sync_once(&mut self) -> Result<Changes> {
        let conn = db::open_readonly(&self.db_path)?;
        self.sync_with(&conn)
    }

    /// Like `sync_once`, reading through the given connection (tests share the engine's).
    pub fn sync_with(&mut self, conn: &Connection) -> Result<Changes> {
        let fs_ = self.fs.clone();
        let snap = Snapshot::begin(conn, &fs_)?;
        let last = self.last_seq();
        if snap.head == last && last > 0 {
            return Ok(Changes::default());
        }
        let changed_docs: BTreeSet<Id> = {
            let mut st =
                conn.prepare("SELECT DISTINCT entry_id FROM doc_updates WHERE seq > ?1")?;
            let v = st
                .query_map([last as i64], |r| r.get::<_, Vec<u8>>(0))?
                .filter_map(|r| r.ok())
                .filter_map(|b| Id::from_slice(&b))
                .collect();
            v
        };
        let p = project(&snap.state, Options::default());
        let rows = self.rows()?;
        let old_path_of: HashMap<Id, String> = rows
            .iter()
            .filter(|(_, r)| r.kind != "dir")
            .map(|(p, r)| (r.entry, p.clone()))
            .collect();
        let desired: BTreeMap<&str, &jess_core::projection::Item> =
            p.items.iter().map(|i| (i.path.as_str(), i)).collect();
        let kind_of = |s: &Source| match s {
            Source::Dir => "dir",
            Source::Text(_) => "text",
            Source::Blob(_) => "blob",
        };
        let mut ch = Changes::default();
        let mut touched_dirs: BTreeSet<PathBuf> = BTreeSet::new();
        // 1. Remove files that are no longer wanted (or change kind).
        for (path, r) in rows.iter().rev() {
            let keep = desired
                .get(path.as_str())
                .map(|i| kind_of(&i.source) == r.kind)
                .unwrap_or(false);
            if keep {
                continue;
            }
            let full = self.root.join(path);
            if r.kind == "dir" {
                let _ = fs::remove_dir(&full); // only if empty; pruned again at the end
            } else {
                match fs::remove_file(&full) {
                    Err(e) if e.kind() != io::ErrorKind::NotFound => return Err(e.into()),
                    _ => {}
                }
                if !snap
                    .state
                    .get(&r.entry)
                    .map(|e| e.is_live())
                    .unwrap_or(false)
                {
                    ch.deleted.push(path.clone());
                }
            }
            self.state
                .execute("DELETE FROM files WHERE path = ?1", [path])?;
            if let Some(parent) = full.parent() {
                touched_dirs.insert(parent.to_path_buf());
            }
        }
        // 2. Directories, parents first.
        let rows = self.rows()?;
        for it in p.items.iter().filter(|i| i.source == Source::Dir) {
            let full = self.root.join(&it.path);
            if full.is_file() {
                fs::remove_file(&full)?;
            }
            if !full.is_dir() {
                fs::create_dir_all(&full)?;
                if let Some(parent) = full.parent() {
                    touched_dirs.insert(parent.to_path_buf());
                }
            }
            if !rows.contains_key(&it.path) {
                self.state.execute(
                    "INSERT OR REPLACE INTO files(path, entry, kind) VALUES (?1, ?2, 'dir')",
                    params![it.path, it.id.0.to_vec()],
                )?;
            }
        }
        // 3. Files.
        for it in p.items.iter().filter(|i| i.source != Source::Dir) {
            let full = self.root.join(&it.path);
            let row = rows.get(&it.path);
            let (want_hash, is_text) = match &it.source {
                Source::Blob(h) => (h.0.to_vec(), false),
                Source::Text(id) => {
                    let unchanged = row
                        .map(|r| r.entry == *id && r.kind == "text")
                        .unwrap_or(false)
                        && !changed_docs.contains(id);
                    if unchanged {
                        continue;
                    }
                    let t = snap.text(*id)?;
                    let h: [u8; 32] = Sha256::digest(t.as_bytes()).into();
                    if row.map(|r| r.hash == h && r.entry == *id).unwrap_or(false) {
                        continue;
                    }
                    self.atomic_bytes(&full, t.as_bytes())?;
                    (h.to_vec(), true)
                }
                Source::Dir => unreachable!(),
            };
            if !is_text {
                if row
                    .map(|r| r.hash == want_hash && r.entry == it.id && full.exists())
                    .unwrap_or(false)
                {
                    continue;
                }
                let Source::Blob(h) = &it.source else {
                    unreachable!()
                };
                if !self.fs.exists(h) {
                    continue; // not uploaded yet; picked up once present (its row seq changes)
                }
                self.link_blob(h, &full)?;
                ch.attachments += 1;
            }
            let m = fs::symlink_metadata(&full)?;
            self.state.execute(
                "INSERT OR REPLACE INTO files(path, entry, kind, hash, size, mtime) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
                params![it.path, it.id.0.to_vec(), if is_text { "text" } else { "blob" }, want_hash, m.len() as i64, mtime_of(&m)],
            )?;
            if let Some(parent) = full.parent() {
                touched_dirs.insert(parent.to_path_buf());
            }
            match (row, old_path_of.get(&it.id)) {
                (None, Some(old)) if old != &it.path => {
                    ch.renamed.push((old.clone(), it.path.clone()))
                }
                (None, _) => ch.added.push(it.path.clone()),
                (Some(_), _) => ch.edited.push(it.path.clone()),
            }
        }
        // Renamed entries were also listed as deletions of their old path: drop those.
        let renamed_from: BTreeSet<&String> = ch.renamed.iter().map(|(a, _)| a).collect();
        ch.deleted.retain(|d| !renamed_from.contains(d));
        // 4. Prune empty directories that aren't vault folders.
        let wanted_dirs: BTreeSet<PathBuf> = p
            .items
            .iter()
            .filter(|i| i.source == Source::Dir)
            .map(|i| self.root.join(&i.path))
            .collect();
        self.prune_empty(&wanted_dirs)?;
        if self.durable {
            for d in touched_dirs {
                let _ = fsync_dir(&d);
            }
        }
        // Blobs still missing on the server keep the mirror "behind" for them; last_seq advances
        // anyway because a later blob row (present) re-triggers a sync.
        self.set_last_seq(snap.head)?;
        Ok(ch)
    }

    fn prune_empty(&self, wanted: &BTreeSet<PathBuf>) -> Result<()> {
        fn walk(d: &Path, root: &Path, wanted: &BTreeSet<PathBuf>) -> io::Result<bool> {
            let mut empty = true;
            for e in fs::read_dir(d)? {
                let e = e?;
                let p = e.path();
                if d == root
                    && (e.file_name() == ".git"
                        || e.file_name() == README
                        || e.file_name() == MARKER)
                {
                    empty = false;
                    continue;
                }
                if e.file_type()?.is_dir() {
                    if walk(&p, root, wanted)? && !wanted.contains(&p) {
                        fs::remove_dir(&p)?;
                    } else {
                        empty = false;
                    }
                } else {
                    empty = false;
                }
            }
            Ok(empty)
        }
        walk(&self.root, &self.root, wanted)?;
        Ok(())
    }

    /// `jess rebuild-mirror`: wipes the mirror (except `.git`) and its state, then regenerates.
    pub fn rebuild(&mut self) -> Result<Changes> {
        for e in fs::read_dir(&self.root)? {
            let e = e?;
            if e.file_name() == ".git" {
                continue;
            }
            if e.file_type()?.is_dir() {
                fs::remove_dir_all(e.path())?;
            } else {
                fs::remove_file(e.path())?;
            }
        }
        self.state
            .execute_batch("DELETE FROM files; DELETE FROM meta;")?;
        self.write_markers()?;
        self.sync_once()
    }
}

/// Reflink (FICLONE) on filesystems that support it (btrfs, xfs).
fn reflink(src: &Path, dst: &Path) -> io::Result<()> {
    use std::os::unix::io::AsRawFd;
    let s = fs::File::open(src)?;
    let d = fs::File::create(dst)?;
    const FICLONE: libc::c_ulong = 0x40049409;
    let r = unsafe { libc::ioctl(d.as_raw_fd(), FICLONE as _, s.as_raw_fd()) };
    if r != 0 {
        let e = io::Error::last_os_error();
        drop(d);
        let _ = fs::remove_file(dst);
        return Err(e);
    }
    Ok(())
}

/// Compares the mirror with the projection of the database (`integrity-check --mirror`).
pub fn check(root: &Path, db_path: &Path, fs_: &BlobFs) -> Result<Vec<String>> {
    let conn = db::open_readonly(db_path)?;
    check_with(root, &conn, fs_)
}

pub fn check_with(root: &Path, conn: &Connection, fs_: &BlobFs) -> Result<Vec<String>> {
    let snap = Snapshot::begin(conn, fs_)?;
    let p = project(&snap.state, Options::default());
    let mut problems = Vec::new();
    let mut expected: BTreeSet<String> = BTreeSet::new();
    for it in &p.items {
        expected.insert(it.path.clone());
        let full = root.join(&it.path);
        match &it.source {
            Source::Dir => {
                if !full.is_dir() {
                    problems.push(format!("mirror: missing folder {}", it.path));
                }
            }
            Source::Text(id) => match fs::read(&full) {
                Ok(b) if b == snap.text(*id)?.into_bytes() => {}
                Ok(_) => problems.push(format!("mirror: {} differs from the database", it.path)),
                Err(_) => problems.push(format!("mirror: missing {}", it.path)),
            },
            Source::Blob(h) => {
                if !fs_.exists(h) {
                    continue;
                }
                match fs::File::open(&full).and_then(|mut f| crate::blobfs::hash_reader(&mut f)) {
                    Ok(x) if x == *h => {}
                    Ok(_) => problems.push(format!("mirror: {} content differs", it.path)),
                    Err(_) => problems.push(format!("mirror: missing {}", it.path)),
                }
            }
        }
    }
    let mut stack = vec![(root.to_path_buf(), String::new())];
    while let Some((d, rel)) = stack.pop() {
        for e in fs::read_dir(&d)?.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            if rel.is_empty() && (name == ".git" || name == README || name == MARKER) {
                continue;
            }
            let r = if rel.is_empty() {
                name.clone()
            } else {
                format!("{rel}/{name}")
            };
            if name.starts_with(".jess-tmp-") {
                problems.push(format!("mirror: stray temp file {r}"));
                continue;
            }
            if !expected.contains(&r) {
                problems.push(format!("mirror: unexpected {r}"));
            }
            if e.file_type()?.is_dir() {
                stack.push((e.path(), r));
            }
        }
    }
    let _ = Error::Injected;
    Ok(problems)
}
